root: wine_quality

data_ingestion:
  root_dir:  wine_quality/data/raw
  source_URL: https://github.com/entbappy/Branching-tutorial/raw/master/winequality-data.zip
  local_data_file: wine_quality/data/raw/data.zip
  unzip_dir: wine_quality/data/raw

data_validation:
  root_dir: wine_quality/data
  unzip_dir: wine_quality/data/raw/wine_quality.csv
  STATUS_FILE: wine_quality/data/status.txt

data_transformation: 
  root_dir: wine_quality/data/processed
  data_path: wine_quality/data/raw

model_trainer:
  root_dir: wine_quality/models
  X_train_path: wine_quality/data/processed/X_train.csv
  X_test_path: wine_quality/data/processed/X_test.csv
  y_train_path: wine_quality/data/processed/y_train.csv
  y_test_path: wine_quality/data/processed/y_test.csv
  model_name: model.joblib

model_evaluation:
  root_dir: wine_quality/metrics
  X_test_path: wine_quality/data/processed/X_test.csv
  y_test_path: wine_quality/data/processed/y_test.csv
  model_path: wine_quality/models/model.joblib
  metric_file_name: wine_quality/metrics/metrics.json
